services:
  - type: web
    name: user-management-api
    runtime: docker
    repo: https://github.com/yourusername/user-management-app
    branch: main
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
